### ISSUE TITLE
Question: Usage of bytea

### ISSUE THREAD

**Issue by smahad786** [bytefish/bytefish.de#36]
I tried to use AbstractMapping with bytea and I got this error. I am able to create pgConnection and I used a simple Java object with UUID and byte[]. I used mapByteArray and I get this error. 

Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 28
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1172)
	at org.postgresql.core.v3.QueryExecutorImpl.startCopy(QueryExecutorImpl.java:881)
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:44)
	at org.postgresql.copy.PGCopyOutputStream.<init>(PGCopyOutputStream.java:45)
	at de.bytefish.pgbulkinsert.PgBulkInsert.saveAll(PgBulkInsert.java:54)
	at com.aexp.rtf.active.bootstrap.PostGresProvenanceSourceTest.bulkInsertEventStateData(PostGresProvenanceSourceTest.java:135)
	at com.aexp.rtf.active.bootstrap.PostGresProvenanceSourceTest.main(PostGresProvenanceSourceTest.java:50)
	Suppressed: de.bytefish.pgbulkinsert.exceptions.BinaryWriteFailedException: java.lang.NullPointerException
		at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:174)
		at de.bytefish.pgbulkinsert.PgBulkInsert.saveAll(PgBulkInsert.java:58)
		... 2 more
	Caused by: java.lang.NullPointerException
		at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:169)
		... 3 more

**Comment by smahad786** [comment]
fixed it. sorry
