### ISSUE TITLE
How can we do the reverting to a particular revision using Versioning and Auditing with spring data Envers? please provider me an example for reverting

### ISSUE THREAD

**Issue by ganeshvidyayug** [bytefish/bytefish.de#53]

**Comment by bytefish** [comment]
Sorry, I am not much into Hibernate Envers anymore and cannot provide an example. I don't think there is a simple way to revert changes using the Envers API, the simplest way is to read the old version and update your entities current values.

**Comment by ganeshvidyayug** [comment]
Hi byteFish, thanks for your response, 
but when am trying the update entity by doing changes from the respective revision , am not able to do, am getting below exception, can you please suggest me the solution

org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:571)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
:
:


Caused by: javax.persistence.RollbackException: Error while committing the transaction
	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
	... 128 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
